# Generated by Zero
# import types as per needed, modify as per your project structure
import enum

from msgspec import Struct

from zero import AsyncZeroClient
from zero.protocols.tcp import AsyncTCPClient

zero_client = AsyncZeroClient("auth", 7101, protocol=AsyncTCPClient)


class Traits(Struct):
    username: str


class RpcClient:
    def __init__(self, zero_client: AsyncZeroClient):
        self._zero_client = zero_client

    async def get_jwt(self, username: str) -> str:
        return await self._zero_client.call("get_jwt", username)

    async def verify_jwt(self, jwt_token: str) -> Traits:
        return await self._zero_client.call("verify_jwt", jwt_token, return_type=Traits)
