# Generated by Zero
# import types as per needed, modify as per your project structure
import enum
from typing import List

from msgspec import Struct

from zero import AsyncZeroClient
from zero.protocols.tcp import AsyncTCPClient

zero_client = AsyncZeroClient("order", 7103, protocol=AsyncTCPClient)


class OrderReq(Struct):
    user_id: int
    items: List[str]


class OrderResp(Struct):
    id: int
    user_id: int
    placed_at: str
    items: List[str]
    status: int


class RpcClient:
    def __init__(self, zero_client: AsyncZeroClient):
        self._zero_client = zero_client

    async def add_order(self, req: OrderReq) -> bool:
        return await self._zero_client.call("add_order", req, return_type=bool)

    async def get_order(self, order_id: int) -> OrderResp:
        return await self._zero_client.call("get_order", order_id, return_type=OrderResp)

    async def get_orders(self, user_id: int) -> List[OrderResp]:
        return await self._zero_client.call("get_orders", user_id, return_type=List[OrderResp])
