# Generated by Zero
# import types as per needed, modify as per your project structure
import enum
from typing import Tuple

from msgspec import Struct

from zero import AsyncZeroClient
from zero.protocols.tcp import AsyncTCPClient

zero_client = AsyncZeroClient("user", 6001, protocol=AsyncTCPClient)


class UserResp(Struct):
    id: int
    username: str


class RpcClient:
    def __init__(self, zero_client: AsyncZeroClient):
        self._zero_client = zero_client

    async def login(self, msg: Tuple[str, str]) -> str:
        return await self._zero_client.call("login", msg)

    async def get_user(self, username: str) -> UserResp:
        return await self._zero_client.call("get_user", username)
