FROM python:3.8-slim

COPY tests/requirements.txt .
RUN pip install -r requirements.txt

COPY zero ./zero
COPY tests ./tests

CMD ["pytest", "tests", "--cov=zero", "--cov-report=term-missing", "-vv"]
